import Gallery from "@/components/Gallery";
import Header from "@/components/Header";
import { client } from "@/lib/client";
import { PhotosT } from "@/types";
import Head from "next/head";

interface Props {
  photos: PhotosT[];
}

export default function Home({ photos }: Props) {
  return (
    <div className="z-0">
      <Head>
        <title>Feli Caffe</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}

      <Header />

      {/* Gallery */}

      <section className="max-w-[95%] mx-auto">
        <Gallery photos={photos} />
      </section>

      {/* Footer */}
    </div>
  );
}

export async function getStaticProps() {
  const query = '*[_type == "photo"]';
  const photos = await client.fetch(query);

  return {
    props: {
      photos,
    },
  };
}
